### ISSUE TITLE
Pagination state Bug?

### ISSUE THREAD

**Issue by Cerya** [Adrian333Dev/filmpire#1]
Hi @Adrian333Dev,

On your demo, From Homepage when you paginate ex: page 2 and then you select a genre category like "Crime" or another categories, pagination is never resetting.

i think it's a bug?

**Comment by asifurrahaman754** [comment]
i can fix it, please assign it to me

**Comment by Adrian333Dev** [comment]
Hey there, thanks for your help but I left Filmpire project,  It's very
basic app

**Comment by Adrian333Dev** [comment]
> i can fix it, please assign it to me

Hey there, I appreciate your help, but I left filmpire project, It's very fundamental project and I don't care about it, However, I gave access to you if you really wanna work on it

**Comment by asifurrahaman754** [comment]
ok, thanks @Adrian333Dev

**Comment by asifurrahaman754** [comment]
@Adrian333Dev I fixed your issue, please check.
